version: "3.9"
services:
  auth-service:
    build:
      context: .
      dockerfile: Auth/Dockerfile
    ports:
      - "8000:8000"
  roster-service:
    build:
      context: .
      dockerfile: Roster/Dockerfile
    ports:
      - "8001:8000"