openapi: 3.0.0
info:
  title: directions-service
  version: '1.0'
  description: API to interface with Google Maps API to find information about a requested route
servers:
  - url: 'http://localhost:8002'
    description: External
  - url: 'http://directions-service:8000'
    description: Internal
paths:
  '/directions/{from}/{to}':
    parameters:
      - schema:
          type: string
        name: from
        in: path
        required: true
        description: Journey Origin Point
      - schema:
          type: string
        name: to
        in: path
        required: true
        description: Journey End Point
    get:
      summary: Get Directions
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  TotalDistance:
                    type: number
                  ARoadDistance:
                    type: number
                required:
                  - TotalDistance
                  - ARoadDistance
              examples:
                example-1:
                  value:
                    TotalDistance: 180887
                    ARoadDistance: 166871
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Could not find route between Exeter and Crediton
      operationId: get-directions-from-to
      description: 'Finds the distance and A-Road distance between {from} and {to}'
components:
  schemas: {}
