openapi: 3.0.0
info:
  title: journey-service
  version: '1.0'
servers:
  - url: 'http://localhost:8003'
    description: External
  - url: 'http://journey-service:8000'
    description: Internal
paths:
  '/journey/{from}/{to}':
    parameters:
      - schema:
          type: string
        name: from
        in: path
        required: true
        description: Journey Origin Point
      - schema:
          type: string
        name: to
        in: path
        required: true
        description: Journey End Point
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  start_point:
                    type: string
                    minLength: 1
                  end_point:
                    type: string
                    minLength: 1
                  total_distance:
                    type: number
                  a_road_distance:
                    type: number
                  best_driver:
                    type: object
                    properties:
                      username:
                        type: string
                        minLength: 1
                      name:
                        type: string
                        minLength: 1
                      rate:
                        type: number
                    required:
                      - username
                      - name
                      - rate
                  cost:
                    type: number
                required:
                  - start_point
                  - end_point
                  - total_distance
                  - a_road_distance
                  - best_driver
                  - cost
              examples:
                example-1:
                  value:
                    start_point: Exeter
                    end_point: 'Crediton, Devon'
                    total_distance: 14007
                    a_road_distance: 13403
                    best_driver:
                      username: babydriver
                      name: Ansel Elgort
                      rate: 15
                    cost: 840420
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Could not fetch route between Exeter and Crediton
                example-2:
                  value:
                    error: Could not fetch roster data
      operationId: get-journey-from-to
      description: 'Returns information about a journey including the distance, chosen driver, and price. '
components:
  schemas: {}
